# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scorecard.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def __init__(self, result):
        self.result = result

    def setupUi(self, Form):
        self.scorecard = self.result[1]

        Form.setObjectName("Form")
        Form.resize(900, 719)
        Form.setMinimumSize(QtCore.QSize(900, 719))
        Form.setMaximumSize(QtCore.QSize(900, 719))
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.team1logo = QtWidgets.QLabel(Form)
        self.team1logo.setMinimumSize(QtCore.QSize(125, 125))
        self.team1logo.setMaximumSize(QtCore.QSize(125, 125))
        self.team1logo.setText("")
        self.team1logo.setPixmap(QtGui.QPixmap("./logos/{}.png".format(self.scorecard[0].name)))
        self.team1logo.setScaledContents(True)
        self.team1logo.setObjectName("team1logo")
        self.horizontalLayout_10.addWidget(self.team1logo)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.match = QtWidgets.QLabel(Form)
        self.match.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.match.setAlignment(QtCore.Qt.AlignCenter)
        self.match.setObjectName("match")
        self.horizontalLayout_3.addWidget(self.match)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toss = QtWidgets.QLabel(Form)
        self.toss.setAlignment(QtCore.Qt.AlignCenter)
        self.toss.setObjectName("toss")
        self.horizontalLayout_4.addWidget(self.toss)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.team1 = QtWidgets.QLabel(Form)
        self.team1.setObjectName("team1")
        self.horizontalLayout_5.addWidget(self.team1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.team2 = QtWidgets.QLabel(Form)
        self.team2.setObjectName("team2")
        self.horizontalLayout_5.addWidget(self.team2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.inning = QtWidgets.QComboBox(Form)
        self.inning.setObjectName("inning")
        self.inning.addItem("")
        self.inning.addItem("")
        self.horizontalLayout_6.addWidget(self.inning)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.team2logo = QtWidgets.QLabel(Form)
        self.team2logo.setMinimumSize(QtCore.QSize(125, 125))
        self.team2logo.setMaximumSize(QtCore.QSize(125, 125))
        self.team2logo.setText("")
        self.team2logo.setPixmap(QtGui.QPixmap("./logos/{}.png".format(self.scorecard[1].name)))
        self.team2logo.setScaledContents(True)
        self.team2logo.setObjectName("team2logo")
        self.horizontalLayout_10.addWidget(self.team2logo)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.batteam = QtWidgets.QLabel(Form)
        self.batteam.setAlignment(QtCore.Qt.AlignCenter)
        self.batteam.setObjectName("batteam")
        self.horizontalLayout_7.addWidget(self.batteam)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setMinimumSize(QtCore.QSize(250, 0))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29)
        self.bat1 = QtWidgets.QLabel(Form)
        self.bat1.setMinimumSize(QtCore.QSize(250, 0))
        self.bat1.setText("")
        self.bat1.setAlignment(QtCore.Qt.AlignCenter)
        self.bat1.setObjectName("bat1")
        self.verticalLayout_3.addWidget(self.bat1)
        self.bat2 = QtWidgets.QLabel(Form)
        self.bat2.setMinimumSize(QtCore.QSize(250, 0))
        self.bat2.setText("")
        self.bat2.setAlignment(QtCore.Qt.AlignCenter)
        self.bat2.setObjectName("bat2")
        self.verticalLayout_3.addWidget(self.bat2)
        self.bat3 = QtWidgets.QLabel(Form)
        self.bat3.setMinimumSize(QtCore.QSize(250, 0))
        self.bat3.setText("")
        self.bat3.setAlignment(QtCore.Qt.AlignCenter)
        self.bat3.setObjectName("bat3")
        self.verticalLayout_3.addWidget(self.bat3)
        self.bat4 = QtWidgets.QLabel(Form)
        self.bat4.setMinimumSize(QtCore.QSize(250, 0))
        self.bat4.setText("")
        self.bat4.setAlignment(QtCore.Qt.AlignCenter)
        self.bat4.setObjectName("bat4")
        self.verticalLayout_3.addWidget(self.bat4)
        self.bat5 = QtWidgets.QLabel(Form)
        self.bat5.setMinimumSize(QtCore.QSize(250, 0))
        self.bat5.setText("")
        self.bat5.setAlignment(QtCore.Qt.AlignCenter)
        self.bat5.setObjectName("bat5")
        self.verticalLayout_3.addWidget(self.bat5)
        self.bat6 = QtWidgets.QLabel(Form)
        self.bat6.setMinimumSize(QtCore.QSize(250, 0))
        self.bat6.setText("")
        self.bat6.setAlignment(QtCore.Qt.AlignCenter)
        self.bat6.setObjectName("bat6")
        self.verticalLayout_3.addWidget(self.bat6)
        self.bat7 = QtWidgets.QLabel(Form)
        self.bat7.setMinimumSize(QtCore.QSize(250, 0))
        self.bat7.setText("")
        self.bat7.setAlignment(QtCore.Qt.AlignCenter)
        self.bat7.setObjectName("bat7")
        self.verticalLayout_3.addWidget(self.bat7)
        self.bat8 = QtWidgets.QLabel(Form)
        self.bat8.setMinimumSize(QtCore.QSize(250, 0))
        self.bat8.setText("")
        self.bat8.setAlignment(QtCore.Qt.AlignCenter)
        self.bat8.setObjectName("bat8")
        self.verticalLayout_3.addWidget(self.bat8)
        self.bat9 = QtWidgets.QLabel(Form)
        self.bat9.setMinimumSize(QtCore.QSize(250, 0))
        self.bat9.setText("")
        self.bat9.setAlignment(QtCore.Qt.AlignCenter)
        self.bat9.setObjectName("bat9")
        self.verticalLayout_3.addWidget(self.bat9)
        self.bat10 = QtWidgets.QLabel(Form)
        self.bat10.setMinimumSize(QtCore.QSize(250, 0))
        self.bat10.setText("")
        self.bat10.setAlignment(QtCore.Qt.AlignCenter)
        self.bat10.setObjectName("bat10")
        self.verticalLayout_3.addWidget(self.bat10)
        self.bat11 = QtWidgets.QLabel(Form)
        self.bat11.setMinimumSize(QtCore.QSize(250, 0))
        self.bat11.setText("")
        self.bat11.setAlignment(QtCore.Qt.AlignCenter)
        self.bat11.setObjectName("bat11")
        self.verticalLayout_3.addWidget(self.bat11)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(75, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_65 = QtWidgets.QLabel(Form)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_6.addWidget(self.label_65)
        self.batrun1 = QtWidgets.QLabel(Form)
        self.batrun1.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun1.setText("")
        self.batrun1.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun1.setObjectName("batrun1")
        self.verticalLayout_6.addWidget(self.batrun1)
        self.batrun2 = QtWidgets.QLabel(Form)
        self.batrun2.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun2.setText("")
        self.batrun2.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun2.setObjectName("batrun2")
        self.verticalLayout_6.addWidget(self.batrun2)
        self.batrun3 = QtWidgets.QLabel(Form)
        self.batrun3.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun3.setText("")
        self.batrun3.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun3.setObjectName("batrun3")
        self.verticalLayout_6.addWidget(self.batrun3)
        self.batrun4 = QtWidgets.QLabel(Form)
        self.batrun4.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun4.setText("")
        self.batrun4.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun4.setObjectName("batrun4")
        self.verticalLayout_6.addWidget(self.batrun4)
        self.batrun5 = QtWidgets.QLabel(Form)
        self.batrun5.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun5.setText("")
        self.batrun5.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun5.setObjectName("batrun5")
        self.verticalLayout_6.addWidget(self.batrun5)
        self.batrun6 = QtWidgets.QLabel(Form)
        self.batrun6.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun6.setText("")
        self.batrun6.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun6.setObjectName("batrun6")
        self.verticalLayout_6.addWidget(self.batrun6)
        self.batrun7 = QtWidgets.QLabel(Form)
        self.batrun7.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun7.setText("")
        self.batrun7.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun7.setObjectName("batrun7")
        self.verticalLayout_6.addWidget(self.batrun7)
        self.batrun8 = QtWidgets.QLabel(Form)
        self.batrun8.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun8.setText("")
        self.batrun8.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun8.setObjectName("batrun8")
        self.verticalLayout_6.addWidget(self.batrun8)
        self.batrun9 = QtWidgets.QLabel(Form)
        self.batrun9.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun9.setText("")
        self.batrun9.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun9.setObjectName("batrun9")
        self.verticalLayout_6.addWidget(self.batrun9)
        self.batrun10 = QtWidgets.QLabel(Form)
        self.batrun10.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun10.setText("")
        self.batrun10.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun10.setObjectName("batrun10")
        self.verticalLayout_6.addWidget(self.batrun10)
        self.batrun11 = QtWidgets.QLabel(Form)
        self.batrun11.setMinimumSize(QtCore.QSize(75, 0))
        self.batrun11.setText("")
        self.batrun11.setAlignment(QtCore.Qt.AlignCenter)
        self.batrun11.setObjectName("batrun11")
        self.verticalLayout_6.addWidget(self.batrun11)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_4.addWidget(self.label_41)
        self.batball1 = QtWidgets.QLabel(Form)
        self.batball1.setMinimumSize(QtCore.QSize(75, 0))
        self.batball1.setText("")
        self.batball1.setAlignment(QtCore.Qt.AlignCenter)
        self.batball1.setObjectName("batball1")
        self.verticalLayout_4.addWidget(self.batball1)
        self.batball2 = QtWidgets.QLabel(Form)
        self.batball2.setMinimumSize(QtCore.QSize(75, 0))
        self.batball2.setText("")
        self.batball2.setAlignment(QtCore.Qt.AlignCenter)
        self.batball2.setObjectName("batball2")
        self.verticalLayout_4.addWidget(self.batball2)
        self.batball3 = QtWidgets.QLabel(Form)
        self.batball3.setMinimumSize(QtCore.QSize(75, 0))
        self.batball3.setText("")
        self.batball3.setAlignment(QtCore.Qt.AlignCenter)
        self.batball3.setObjectName("batball3")
        self.verticalLayout_4.addWidget(self.batball3)
        self.batball4 = QtWidgets.QLabel(Form)
        self.batball4.setMinimumSize(QtCore.QSize(75, 0))
        self.batball4.setText("")
        self.batball4.setAlignment(QtCore.Qt.AlignCenter)
        self.batball4.setObjectName("batball4")
        self.verticalLayout_4.addWidget(self.batball4)
        self.batball5 = QtWidgets.QLabel(Form)
        self.batball5.setMinimumSize(QtCore.QSize(75, 0))
        self.batball5.setText("")
        self.batball5.setAlignment(QtCore.Qt.AlignCenter)
        self.batball5.setObjectName("batball5")
        self.verticalLayout_4.addWidget(self.batball5)
        self.batball6 = QtWidgets.QLabel(Form)
        self.batball6.setMinimumSize(QtCore.QSize(75, 0))
        self.batball6.setText("")
        self.batball6.setAlignment(QtCore.Qt.AlignCenter)
        self.batball6.setObjectName("batball6")
        self.verticalLayout_4.addWidget(self.batball6)
        self.batball7 = QtWidgets.QLabel(Form)
        self.batball7.setMinimumSize(QtCore.QSize(75, 0))
        self.batball7.setText("")
        self.batball7.setAlignment(QtCore.Qt.AlignCenter)
        self.batball7.setObjectName("batball7")
        self.verticalLayout_4.addWidget(self.batball7)
        self.batball8 = QtWidgets.QLabel(Form)
        self.batball8.setMinimumSize(QtCore.QSize(75, 0))
        self.batball8.setText("")
        self.batball8.setAlignment(QtCore.Qt.AlignCenter)
        self.batball8.setObjectName("batball8")
        self.verticalLayout_4.addWidget(self.batball8)
        self.batball9 = QtWidgets.QLabel(Form)
        self.batball9.setMinimumSize(QtCore.QSize(75, 0))
        self.batball9.setText("")
        self.batball9.setAlignment(QtCore.Qt.AlignCenter)
        self.batball9.setObjectName("batball9")
        self.verticalLayout_4.addWidget(self.batball9)
        self.batball10 = QtWidgets.QLabel(Form)
        self.batball10.setMinimumSize(QtCore.QSize(75, 0))
        self.batball10.setText("")
        self.batball10.setAlignment(QtCore.Qt.AlignCenter)
        self.batball10.setObjectName("batball10")
        self.verticalLayout_4.addWidget(self.batball10)
        self.batball11 = QtWidgets.QLabel(Form)
        self.batball11.setMinimumSize(QtCore.QSize(75, 0))
        self.batball11.setText("")
        self.batball11.setAlignment(QtCore.Qt.AlignCenter)
        self.batball11.setObjectName("batball11")
        self.verticalLayout_4.addWidget(self.batball11)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.bat61 = QtWidgets.QLabel(Form)
        self.bat61.setMinimumSize(QtCore.QSize(75, 0))
        self.bat61.setText("")
        self.bat61.setAlignment(QtCore.Qt.AlignCenter)
        self.bat61.setObjectName("bat61")
        self.verticalLayout_2.addWidget(self.bat61)
        self.bat62 = QtWidgets.QLabel(Form)
        self.bat62.setMinimumSize(QtCore.QSize(75, 0))
        self.bat62.setText("")
        self.bat62.setAlignment(QtCore.Qt.AlignCenter)
        self.bat62.setObjectName("bat62")
        self.verticalLayout_2.addWidget(self.bat62)
        self.bat63 = QtWidgets.QLabel(Form)
        self.bat63.setMinimumSize(QtCore.QSize(75, 0))
        self.bat63.setText("")
        self.bat63.setAlignment(QtCore.Qt.AlignCenter)
        self.bat63.setObjectName("bat63")
        self.verticalLayout_2.addWidget(self.bat63)
        self.bat64 = QtWidgets.QLabel(Form)
        self.bat64.setMinimumSize(QtCore.QSize(75, 0))
        self.bat64.setText("")
        self.bat64.setAlignment(QtCore.Qt.AlignCenter)
        self.bat64.setObjectName("bat64")
        self.verticalLayout_2.addWidget(self.bat64)
        self.bat65 = QtWidgets.QLabel(Form)
        self.bat65.setMinimumSize(QtCore.QSize(75, 0))
        self.bat65.setText("")
        self.bat65.setAlignment(QtCore.Qt.AlignCenter)
        self.bat65.setObjectName("bat65")
        self.verticalLayout_2.addWidget(self.bat65)
        self.bat66 = QtWidgets.QLabel(Form)
        self.bat66.setMinimumSize(QtCore.QSize(75, 0))
        self.bat66.setText("")
        self.bat66.setAlignment(QtCore.Qt.AlignCenter)
        self.bat66.setObjectName("bat66")
        self.verticalLayout_2.addWidget(self.bat66)
        self.bat67 = QtWidgets.QLabel(Form)
        self.bat67.setMinimumSize(QtCore.QSize(75, 0))
        self.bat67.setText("")
        self.bat67.setAlignment(QtCore.Qt.AlignCenter)
        self.bat67.setObjectName("bat67")
        self.verticalLayout_2.addWidget(self.bat67)
        self.bat68 = QtWidgets.QLabel(Form)
        self.bat68.setMinimumSize(QtCore.QSize(75, 0))
        self.bat68.setText("")
        self.bat68.setAlignment(QtCore.Qt.AlignCenter)
        self.bat68.setObjectName("bat68")
        self.verticalLayout_2.addWidget(self.bat68)
        self.bat69 = QtWidgets.QLabel(Form)
        self.bat69.setMinimumSize(QtCore.QSize(75, 0))
        self.bat69.setText("")
        self.bat69.setAlignment(QtCore.Qt.AlignCenter)
        self.bat69.setObjectName("bat69")
        self.verticalLayout_2.addWidget(self.bat69)
        self.bat610 = QtWidgets.QLabel(Form)
        self.bat610.setMinimumSize(QtCore.QSize(75, 0))
        self.bat610.setText("")
        self.bat610.setAlignment(QtCore.Qt.AlignCenter)
        self.bat610.setObjectName("bat610")
        self.verticalLayout_2.addWidget(self.bat610)
        self.bat611 = QtWidgets.QLabel(Form)
        self.bat611.setMinimumSize(QtCore.QSize(75, 0))
        self.bat611.setText("")
        self.bat611.setAlignment(QtCore.Qt.AlignCenter)
        self.bat611.setObjectName("bat611")
        self.verticalLayout_2.addWidget(self.bat611)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.bat41 = QtWidgets.QLabel(Form)
        self.bat41.setMinimumSize(QtCore.QSize(75, 0))
        self.bat41.setText("")
        self.bat41.setAlignment(QtCore.Qt.AlignCenter)
        self.bat41.setObjectName("bat41")
        self.verticalLayout.addWidget(self.bat41)
        self.bat42 = QtWidgets.QLabel(Form)
        self.bat42.setMinimumSize(QtCore.QSize(75, 0))
        self.bat42.setText("")
        self.bat42.setAlignment(QtCore.Qt.AlignCenter)
        self.bat42.setObjectName("bat42")
        self.verticalLayout.addWidget(self.bat42)
        self.bat43 = QtWidgets.QLabel(Form)
        self.bat43.setMinimumSize(QtCore.QSize(75, 0))
        self.bat43.setText("")
        self.bat43.setAlignment(QtCore.Qt.AlignCenter)
        self.bat43.setObjectName("bat43")
        self.verticalLayout.addWidget(self.bat43)
        self.bat44 = QtWidgets.QLabel(Form)
        self.bat44.setMinimumSize(QtCore.QSize(75, 0))
        self.bat44.setText("")
        self.bat44.setAlignment(QtCore.Qt.AlignCenter)
        self.bat44.setObjectName("bat44")
        self.verticalLayout.addWidget(self.bat44)
        self.bat45 = QtWidgets.QLabel(Form)
        self.bat45.setMinimumSize(QtCore.QSize(75, 0))
        self.bat45.setText("")
        self.bat45.setAlignment(QtCore.Qt.AlignCenter)
        self.bat45.setObjectName("bat45")
        self.verticalLayout.addWidget(self.bat45)
        self.bat46 = QtWidgets.QLabel(Form)
        self.bat46.setMinimumSize(QtCore.QSize(75, 0))
        self.bat46.setText("")
        self.bat46.setAlignment(QtCore.Qt.AlignCenter)
        self.bat46.setObjectName("bat46")
        self.verticalLayout.addWidget(self.bat46)
        self.bat47 = QtWidgets.QLabel(Form)
        self.bat47.setMinimumSize(QtCore.QSize(75, 0))
        self.bat47.setText("")
        self.bat47.setAlignment(QtCore.Qt.AlignCenter)
        self.bat47.setObjectName("bat47")
        self.verticalLayout.addWidget(self.bat47)
        self.bat48 = QtWidgets.QLabel(Form)
        self.bat48.setMinimumSize(QtCore.QSize(75, 0))
        self.bat48.setText("")
        self.bat48.setAlignment(QtCore.Qt.AlignCenter)
        self.bat48.setObjectName("bat48")
        self.verticalLayout.addWidget(self.bat48)
        self.bat49 = QtWidgets.QLabel(Form)
        self.bat49.setMinimumSize(QtCore.QSize(75, 0))
        self.bat49.setText("")
        self.bat49.setAlignment(QtCore.Qt.AlignCenter)
        self.bat49.setObjectName("bat49")
        self.verticalLayout.addWidget(self.bat49)
        self.bat410 = QtWidgets.QLabel(Form)
        self.bat410.setMinimumSize(QtCore.QSize(75, 0))
        self.bat410.setText("")
        self.bat410.setAlignment(QtCore.Qt.AlignCenter)
        self.bat410.setObjectName("bat410")
        self.verticalLayout.addWidget(self.bat410)
        self.bat411 = QtWidgets.QLabel(Form)
        self.bat411.setMinimumSize(QtCore.QSize(75, 0))
        self.bat411.setText("")
        self.bat411.setAlignment(QtCore.Qt.AlignCenter)
        self.bat411.setObjectName("bat411")
        self.verticalLayout.addWidget(self.bat411)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_5.addWidget(self.label_53)
        self.batsr1 = QtWidgets.QLabel(Form)
        self.batsr1.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr1.setText("")
        self.batsr1.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr1.setObjectName("batsr1")
        self.verticalLayout_5.addWidget(self.batsr1)
        self.batsr2 = QtWidgets.QLabel(Form)
        self.batsr2.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr2.setText("")
        self.batsr2.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr2.setObjectName("batsr2")
        self.verticalLayout_5.addWidget(self.batsr2)
        self.batsr3 = QtWidgets.QLabel(Form)
        self.batsr3.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr3.setText("")
        self.batsr3.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr3.setObjectName("batsr3")
        self.verticalLayout_5.addWidget(self.batsr3)
        self.batsr4 = QtWidgets.QLabel(Form)
        self.batsr4.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr4.setText("")
        self.batsr4.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr4.setObjectName("batsr4")
        self.verticalLayout_5.addWidget(self.batsr4)
        self.batsr5 = QtWidgets.QLabel(Form)
        self.batsr5.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr5.setText("")
        self.batsr5.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr5.setObjectName("batsr5")
        self.verticalLayout_5.addWidget(self.batsr5)
        self.batsr6 = QtWidgets.QLabel(Form)
        self.batsr6.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr6.setText("")
        self.batsr6.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr6.setObjectName("batsr6")
        self.verticalLayout_5.addWidget(self.batsr6)
        self.batsr7 = QtWidgets.QLabel(Form)
        self.batsr7.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr7.setText("")
        self.batsr7.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr7.setObjectName("batsr7")
        self.verticalLayout_5.addWidget(self.batsr7)
        self.batsr8 = QtWidgets.QLabel(Form)
        self.batsr8.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr8.setText("")
        self.batsr8.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr8.setObjectName("batsr8")
        self.verticalLayout_5.addWidget(self.batsr8)
        self.batsr9 = QtWidgets.QLabel(Form)
        self.batsr9.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr9.setText("")
        self.batsr9.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr9.setObjectName("batsr9")
        self.verticalLayout_5.addWidget(self.batsr9)
        self.batsr10 = QtWidgets.QLabel(Form)
        self.batsr10.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr10.setText("")
        self.batsr10.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr10.setObjectName("batsr10")
        self.verticalLayout_5.addWidget(self.batsr10)
        self.batsr11 = QtWidgets.QLabel(Form)
        self.batsr11.setMinimumSize(QtCore.QSize(75, 0))
        self.batsr11.setText("")
        self.batsr11.setAlignment(QtCore.Qt.AlignCenter)
        self.batsr11.setObjectName("batsr11")
        self.verticalLayout_5.addWidget(self.batsr11)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bowlteam = QtWidgets.QLabel(Form)
        self.bowlteam.setAlignment(QtCore.Qt.AlignCenter)
        self.bowlteam.setObjectName("bowlteam")
        self.horizontalLayout_8.addWidget(self.bowlteam)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_84 = QtWidgets.QLabel(Form)
        self.label_84.setMinimumSize(QtCore.QSize(250, 0))
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_8.addWidget(self.label_84)
        self.ball1 = QtWidgets.QLabel(Form)
        self.ball1.setMinimumSize(QtCore.QSize(250, 0))
        self.ball1.setText("")
        self.ball1.setAlignment(QtCore.Qt.AlignCenter)
        self.ball1.setObjectName("ball1")
        self.verticalLayout_8.addWidget(self.ball1)
        self.ball2 = QtWidgets.QLabel(Form)
        self.ball2.setMinimumSize(QtCore.QSize(250, 0))
        self.ball2.setText("")
        self.ball2.setAlignment(QtCore.Qt.AlignCenter)
        self.ball2.setObjectName("ball2")
        self.verticalLayout_8.addWidget(self.ball2)
        self.ball3 = QtWidgets.QLabel(Form)
        self.ball3.setMinimumSize(QtCore.QSize(250, 0))
        self.ball3.setText("")
        self.ball3.setAlignment(QtCore.Qt.AlignCenter)
        self.ball3.setObjectName("ball3")
        self.verticalLayout_8.addWidget(self.ball3)
        self.ball4 = QtWidgets.QLabel(Form)
        self.ball4.setMinimumSize(QtCore.QSize(250, 0))
        self.ball4.setText("")
        self.ball4.setAlignment(QtCore.Qt.AlignCenter)
        self.ball4.setObjectName("ball4")
        self.verticalLayout_8.addWidget(self.ball4)
        self.ball5 = QtWidgets.QLabel(Form)
        self.ball5.setMinimumSize(QtCore.QSize(250, 0))
        self.ball5.setText("")
        self.ball5.setAlignment(QtCore.Qt.AlignCenter)
        self.ball5.setObjectName("ball5")
        self.verticalLayout_8.addWidget(self.ball5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_96 = QtWidgets.QLabel(Form)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_10.addWidget(self.label_96)
        self.ballrun1 = QtWidgets.QLabel(Form)
        self.ballrun1.setText("")
        self.ballrun1.setAlignment(QtCore.Qt.AlignCenter)
        self.ballrun1.setObjectName("ballrun1")
        self.verticalLayout_10.addWidget(self.ballrun1)
        self.ballrun2 = QtWidgets.QLabel(Form)
        self.ballrun2.setText("")
        self.ballrun2.setAlignment(QtCore.Qt.AlignCenter)
        self.ballrun2.setObjectName("ballrun2")
        self.verticalLayout_10.addWidget(self.ballrun2)
        self.ballrun3 = QtWidgets.QLabel(Form)
        self.ballrun3.setMinimumSize(QtCore.QSize(96, 0))
        self.ballrun3.setText("")
        self.ballrun3.setAlignment(QtCore.Qt.AlignCenter)
        self.ballrun3.setObjectName("ballrun3")
        self.verticalLayout_10.addWidget(self.ballrun3)
        self.ballrun4 = QtWidgets.QLabel(Form)
        self.ballrun4.setMinimumSize(QtCore.QSize(96, 0))
        self.ballrun4.setText("")
        self.ballrun4.setAlignment(QtCore.Qt.AlignCenter)
        self.ballrun4.setObjectName("ballrun4")
        self.verticalLayout_10.addWidget(self.ballrun4)
        self.ballrun5 = QtWidgets.QLabel(Form)
        self.ballrun5.setMinimumSize(QtCore.QSize(96, 0))
        self.ballrun5.setText("")
        self.ballrun5.setAlignment(QtCore.Qt.AlignCenter)
        self.ballrun5.setObjectName("ballrun5")
        self.verticalLayout_10.addWidget(self.ballrun5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_78 = QtWidgets.QLabel(Form)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_7.addWidget(self.label_78)
        self.ballover1 = QtWidgets.QLabel(Form)
        self.ballover1.setText("")
        self.ballover1.setAlignment(QtCore.Qt.AlignCenter)
        self.ballover1.setObjectName("ballover1")
        self.verticalLayout_7.addWidget(self.ballover1)
        self.ballover2 = QtWidgets.QLabel(Form)
        self.ballover2.setText("")
        self.ballover2.setAlignment(QtCore.Qt.AlignCenter)
        self.ballover2.setObjectName("ballover2")
        self.verticalLayout_7.addWidget(self.ballover2)
        self.ballover3 = QtWidgets.QLabel(Form)
        self.ballover3.setMinimumSize(QtCore.QSize(96, 0))
        self.ballover3.setText("")
        self.ballover3.setAlignment(QtCore.Qt.AlignCenter)
        self.ballover3.setObjectName("ballover3")
        self.verticalLayout_7.addWidget(self.ballover3)
        self.ballover4 = QtWidgets.QLabel(Form)
        self.ballover4.setMinimumSize(QtCore.QSize(96, 0))
        self.ballover4.setText("")
        self.ballover4.setAlignment(QtCore.Qt.AlignCenter)
        self.ballover4.setObjectName("ballover4")
        self.verticalLayout_7.addWidget(self.ballover4)
        self.ballover5 = QtWidgets.QLabel(Form)
        self.ballover5.setMinimumSize(QtCore.QSize(96, 0))
        self.ballover5.setText("")
        self.ballover5.setAlignment(QtCore.Qt.AlignCenter)
        self.ballover5.setObjectName("ballover5")
        self.verticalLayout_7.addWidget(self.ballover5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_102 = QtWidgets.QLabel(Form)
        self.label_102.setObjectName("label_102")
        self.verticalLayout_11.addWidget(self.label_102)
        self.ballwkt1 = QtWidgets.QLabel(Form)
        self.ballwkt1.setText("")
        self.ballwkt1.setAlignment(QtCore.Qt.AlignCenter)
        self.ballwkt1.setObjectName("ballwkt1")
        self.verticalLayout_11.addWidget(self.ballwkt1)
        self.ballwkt2 = QtWidgets.QLabel(Form)
        self.ballwkt2.setText("")
        self.ballwkt2.setAlignment(QtCore.Qt.AlignCenter)
        self.ballwkt2.setObjectName("ballwkt2")
        self.verticalLayout_11.addWidget(self.ballwkt2)
        self.ballwkt3 = QtWidgets.QLabel(Form)
        self.ballwkt3.setMinimumSize(QtCore.QSize(96, 0))
        self.ballwkt3.setText("")
        self.ballwkt3.setAlignment(QtCore.Qt.AlignCenter)
        self.ballwkt3.setObjectName("ballwkt3")
        self.verticalLayout_11.addWidget(self.ballwkt3)
        self.ballwkt4 = QtWidgets.QLabel(Form)
        self.ballwkt4.setMinimumSize(QtCore.QSize(96, 0))
        self.ballwkt4.setText("")
        self.ballwkt4.setAlignment(QtCore.Qt.AlignCenter)
        self.ballwkt4.setObjectName("ballwkt4")
        self.verticalLayout_11.addWidget(self.ballwkt4)
        self.ballwkt5 = QtWidgets.QLabel(Form)
        self.ballwkt5.setMinimumSize(QtCore.QSize(96, 0))
        self.ballwkt5.setText("")
        self.ballwkt5.setAlignment(QtCore.Qt.AlignCenter)
        self.ballwkt5.setObjectName("ballwkt5")
        self.verticalLayout_11.addWidget(self.ballwkt5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_90 = QtWidgets.QLabel(Form)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_9.addWidget(self.label_90)
        self.balleco1 = QtWidgets.QLabel(Form)
        self.balleco1.setText("")
        self.balleco1.setAlignment(QtCore.Qt.AlignCenter)
        self.balleco1.setObjectName("balleco1")
        self.verticalLayout_9.addWidget(self.balleco1)
        self.balleco2 = QtWidgets.QLabel(Form)
        self.balleco2.setText("")
        self.balleco2.setAlignment(QtCore.Qt.AlignCenter)
        self.balleco2.setObjectName("balleco2")
        self.verticalLayout_9.addWidget(self.balleco2)
        self.balleco3 = QtWidgets.QLabel(Form)
        self.balleco3.setMinimumSize(QtCore.QSize(96, 0))
        self.balleco3.setText("")
        self.balleco3.setAlignment(QtCore.Qt.AlignCenter)
        self.balleco3.setObjectName("balleco3")
        self.verticalLayout_9.addWidget(self.balleco3)
        self.balleco4 = QtWidgets.QLabel(Form)
        self.balleco4.setMinimumSize(QtCore.QSize(96, 0))
        self.balleco4.setText("")
        self.balleco4.setAlignment(QtCore.Qt.AlignCenter)
        self.balleco4.setObjectName("balleco4")
        self.verticalLayout_9.addWidget(self.balleco4)
        self.balleco5 = QtWidgets.QLabel(Form)
        self.balleco5.setMinimumSize(QtCore.QSize(96, 0))
        self.balleco5.setText("")
        self.balleco5.setAlignment(QtCore.Qt.AlignCenter)
        self.balleco5.setObjectName("balleco5")
        self.verticalLayout_9.addWidget(self.balleco5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def fill_scorecard(self):
        index = self.result[0][0]
        if self.inning.currentIndex() == 1:
            index = (self.result[0][0] + 1) % 2
        team = self.scorecard[index]

        _translate = QtCore.QCoreApplication.translate
        self.batteam.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">{}</span></p></body></html>".format(team.name)))
        self.bowlteam.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">{}</span></p></body></html>".format(team.opponent_name)))

        batsmen = team.batsmen
        self.bat1.setText(batsmen[0].name)
        self.bat2.setText(batsmen[1].name)
        self.bat3.setText(batsmen[2].name)
        self.bat4.setText(batsmen[3].name)
        self.bat5.setText(batsmen[4].name)
        self.bat6.setText(batsmen[5].name)
        self.bat7.setText(batsmen[6].name)
        self.bat8.setText(batsmen[7].name)
        self.bat9.setText(batsmen[8].name)
        self.bat10.setText(batsmen[9].name)
        self.bat11.setText(batsmen[10].name)

        if batsmen[0].batted:
            self.batrun1.setText('{}'.format(batsmen[0].runs) + batsmen[0].asterisk())
            self.batball1.setText('{}'.format(batsmen[0].balls))
            self.bat61.setText('{}'.format(batsmen[0].sixes))
            self.bat41.setText('{}'.format(batsmen[0].fours))
            self.batsr1.setText('{}'.format(batsmen[0].strike_rate))
        else:
            self.batrun1.setText('')
            self.batball1.setText('')
            self.bat61.setText('')
            self.bat41.setText('')
            self.batsr1.setText('')

        if batsmen[1].batted:
            self.batrun2.setText('{}'.format(batsmen[1].runs) + batsmen[1].asterisk())
            self.batball2.setText('{}'.format(batsmen[1].balls))
            self.bat62.setText('{}'.format(batsmen[1].sixes))
            self.bat42.setText('{}'.format(batsmen[1].fours))
            self.batsr2.setText('{}'.format(batsmen[1].strike_rate))
        else:
            self.batrun2.setText('')
            self.batball2.setText('')
            self.bat62.setText('')
            self.bat42.setText('')
            self.batsr2.setText('')

        if batsmen[2].batted:
            self.batrun3.setText('{}'.format(batsmen[2].runs) + batsmen[2].asterisk())
            self.batball3.setText('{}'.format(batsmen[2].balls))
            self.bat63.setText('{}'.format(batsmen[2].sixes))
            self.bat43.setText('{}'.format(batsmen[2].fours))
            self.batsr3.setText('{}'.format(batsmen[2].strike_rate))
        else:
            self.batrun3.setText('')
            self.batball3.setText('')
            self.bat63.setText('')
            self.bat43.setText('')
            self.batsr3.setText('')

        if batsmen[3].batted:
            self.batrun4.setText('{}'.format(batsmen[3].runs) + batsmen[3].asterisk())
            self.batball4.setText('{}'.format(batsmen[3].balls))
            self.bat64.setText('{}'.format(batsmen[3].sixes))
            self.bat44.setText('{}'.format(batsmen[3].fours))
            self.batsr4.setText('{}'.format(batsmen[3].strike_rate))
        else:
            self.batrun4.setText('')
            self.batball4.setText('')
            self.bat64.setText('')
            self.bat44.setText('')
            self.batsr4.setText('')

        if batsmen[4].batted:
            self.batrun5.setText('{}'.format(batsmen[4].runs) + batsmen[4].asterisk())
            self.batball5.setText('{}'.format(batsmen[4].balls))
            self.bat65.setText('{}'.format(batsmen[4].sixes))
            self.bat45.setText('{}'.format(batsmen[4].fours))
            self.batsr5.setText('{}'.format(batsmen[4].strike_rate))
        else:
            self.batrun5.setText('')
            self.batball5.setText('')
            self.bat65.setText('')
            self.bat45.setText('')
            self.batsr5.setText('')

        if batsmen[5].batted:
            self.batrun6.setText('{}'.format(batsmen[5].runs) + batsmen[5].asterisk())
            self.batball6.setText('{}'.format(batsmen[5].balls))
            self.bat66.setText('{}'.format(batsmen[5].sixes))
            self.bat46.setText('{}'.format(batsmen[5].fours))
            self.batsr6.setText('{}'.format(batsmen[5].strike_rate))
        else:
            self.batrun6.setText('')
            self.batball6.setText('')
            self.bat66.setText('')
            self.bat46.setText('')
            self.batsr6.setText('')

        if batsmen[6].batted:
            self.batrun7.setText('{}'.format(batsmen[6].runs) + batsmen[6].asterisk())
            self.batball7.setText('{}'.format(batsmen[6].balls))
            self.bat67.setText('{}'.format(batsmen[6].sixes))
            self.bat47.setText('{}'.format(batsmen[6].fours))
            self.batsr7.setText('{}'.format(batsmen[6].strike_rate))
        else:
            self.batrun7.setText('')
            self.batball7.setText('')
            self.bat67.setText('')
            self.bat47.setText('')
            self.batsr7.setText('')

        if batsmen[7].batted:
            self.batrun8.setText('{}'.format(batsmen[7].runs) + batsmen[7].asterisk())
            self.batball8.setText('{}'.format(batsmen[7].balls))
            self.bat68.setText('{}'.format(batsmen[7].sixes))
            self.bat48.setText('{}'.format(batsmen[7].fours))
            self.batsr8.setText('{}'.format(batsmen[7].strike_rate))
        else:
            self.batrun8.setText('')
            self.batball8.setText('')
            self.bat68.setText('')
            self.bat48.setText('')
            self.batsr8.setText('')

        if batsmen[8].batted:
            self.batrun9.setText('{}'.format(batsmen[8].runs) + batsmen[8].asterisk())
            self.batball9.setText('{}'.format(batsmen[8].balls))
            self.bat69.setText('{}'.format(batsmen[8].sixes))
            self.bat49.setText('{}'.format(batsmen[8].fours))
            self.batsr9.setText('{}'.format(batsmen[8].strike_rate))
        else:
            self.batrun9.setText('')
            self.batball9.setText('')
            self.bat69.setText('')
            self.bat49.setText('')
            self.batsr9.setText('')

        if batsmen[9].batted:
            self.batrun10.setText('{}'.format(batsmen[9].runs) + batsmen[9].asterisk())
            self.batball10.setText('{}'.format(batsmen[9].balls))
            self.bat610.setText('{}'.format(batsmen[9].sixes))
            self.bat410.setText('{}'.format(batsmen[9].fours))
            self.batsr10.setText('{}'.format(batsmen[9].strike_rate))
        else:
            self.batrun10.setText('')
            self.batball10.setText('')
            self.bat610.setText('')
            self.bat410.setText('')
            self.batsr10.setText('')

        if batsmen[10].batted:
            self.batrun11.setText('{}'.format(batsmen[10].runs) + batsmen[10].asterisk())
            self.batball11.setText('{}'.format(batsmen[10].balls))
            self.bat611.setText('{}'.format(batsmen[10].sixes))
            self.bat411.setText('{}'.format(batsmen[10].fours))
            self.batsr11.setText('{}'.format(batsmen[10].strike_rate))
        else:
            self.batrun11.setText('')
            self.batball11.setText('')
            self.bat611.setText('')
            self.bat411.setText('')
            self.batsr11.setText('')

        bowlers = team.bowler

        if bowlers[0].balls > 0:
            self.ball1.setText('{}'.format(bowlers[0].name))
            self.ballrun1.setText('{}'.format(bowlers[0].runs))
            self.ballover1.setText('{}'.format(bowlers[0].overs()))
            self.ballwkt1.setText('{}'.format(bowlers[0].wicket))
            self.balleco1.setText('{}'.format(bowlers[0].economy))
        else:
            self.ball1.setText('')
            self.ballrun1.setText('')
            self.ballover1.setText('')
            self.ballwkt1.setText('')
            self.balleco1.setText('')

        if bowlers[1].balls > 0:
            self.ball2.setText('{}'.format(bowlers[1].name))
            self.ballrun2.setText('{}'.format(bowlers[1].runs))
            self.ballover2.setText('{}'.format(bowlers[1].overs()))
            self.ballwkt2.setText('{}'.format(bowlers[1].wicket))
            self.balleco2.setText('{}'.format(bowlers[1].economy))
        else:
            self.ball2.setText('')
            self.ballrun2.setText('')
            self.ballover2.setText('')
            self.ballwkt2.setText('')
            self.balleco2.setText('')

        if bowlers[2].balls > 0:
            self.ball3.setText('{}'.format(bowlers[2].name))
            self.ballrun3.setText('{}'.format(bowlers[2].runs))
            self.ballover3.setText('{}'.format(bowlers[2].overs()))
            self.ballwkt3.setText('{}'.format(bowlers[2].wicket))
            self.balleco3.setText('{}'.format(bowlers[2].economy))
        else:
            self.ball3.setText('')
            self.ballrun3.setText('')
            self.ballover3.setText('')
            self.ballwkt3.setText('')
            self.balleco3.setText('')

        if bowlers[3].balls > 0:
            self.ball4.setText('{}'.format(bowlers[3].name))
            self.ballrun4.setText('{}'.format(bowlers[3].runs))
            self.ballover4.setText('{}'.format(bowlers[3].overs()))
            self.ballwkt4.setText('{}'.format(bowlers[3].wicket))
            self.balleco4.setText('{}'.format(bowlers[3].economy))
        else:
            self.ball4.setText('')
            self.ballrun4.setText('')
            self.ballover4.setText('')
            self.ballwkt4.setText('')
            self.balleco4.setText('')

        if bowlers[4].balls > 0:
            self.ball5.setText('{}'.format(bowlers[4].name))
            self.ballrun5.setText('{}'.format(bowlers[4].runs))
            self.ballover5.setText('{}'.format(bowlers[4].overs()))
            self.ballwkt5.setText('{}'.format(bowlers[4].wicket))
            self.balleco5.setText('{}'.format(bowlers[4].economy))
        else:
            self.ball5.setText('')
            self.ballrun5.setText('')
            self.ballover5.setText('')
            self.ballwkt5.setText('')
            self.balleco5.setText('')


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Scorecard"))
        self.match.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">{} vs {}</span></p></body></html>".format(self.scorecard[0].name, self.scorecard[1].name)))
        self.toss.setText(_translate("Form", self.result[0][1]))
        self.team1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">{}</span>: {}/{} in {} Overs</p></body></html>".format(self.scorecard[0].name, self.scorecard[0].score, self.scorecard[0].wickets, self.scorecard[0].overs())))
        self.team2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">{}</span>: {}/{} in {} Overs</p></body></html>".format(self.scorecard[1].name, self.scorecard[1].score, self.scorecard[1].wickets, self.scorecard[1].overs())))
        self.inning.setItemText(0, _translate("Form", "Inning 1"))
        self.inning.setItemText(1, _translate("Form", "Inning 2"))
        self.batteam.setText(_translate("Form", "India"))
        self.label_29.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Batsman</span></p></body></html>"))
        self.label_65.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Runs</span></p></body></html>"))
        self.label_41.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Balls</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">6s</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">4s</span></p></body></html>"))
        self.label_53.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SR</span></p></body></html>"))
        self.bowlteam.setText(_translate("Form", "Australia"))
        self.label_84.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Bowler</span></p></body></html>"))
        self.label_96.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Runs</span></p></body></html>"))
        self.label_78.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Overs</span></p></body></html>"))
        self.label_102.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">WIckets</span></p></body></html>"))
        self.label_90.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Economy</span></p></body></html>"))


        self.fill_scorecard()
        self.inning.currentIndexChanged.connect(self.fill_scorecard)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
